name: tests
on:
  push:

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: checkout razorpay
        uses: actions/checkout@v2
      - name: test
        run: make test
